# Generated by Django 2.0 on 2018-01-05 01:27

import ComeHome.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ComeHome.models.scramble_uploaded_fileName)),
                ('Photographer', models.CharField(max_length=200)),
                ('originalAddress', models.URLField()),
            ],
        ),
    ]
